/* eslint-disable */
// This file is auto-generated by scripts/generate-components-gallery.mjs
import React from 'react';

import { Accordion } from '../../Accordion/Accordion';
import { Avatar } from '../../Avatar/Avatar';
import { Badge } from '../../Badge/Badge';
import { Bar } from '../../Bar/Bar';
import { Breadcrumb } from '../../Breadcrumb/Breadcrumb';
import { Button } from '../../Button/Button';
import { Calendar } from '../../Calendar/Calendar';
import { Card } from '../../Card/Card';
import { Carousel } from '../../Carousel/Carousel';
import { Checkbox } from '../../Checkbox/Checkbox';
import { Code } from '../../Code/Code';
import { Command } from '../../Command/Command';
import { DatePicker } from '../../DatePicker/DatePicker';
import { Drawer } from '../../Drawer/Drawer';
import { Icon } from '../../Icon/Icon';
import { Input } from '../../Input/Input';
import { Markdown } from '../../Markdown/Markdown';
import { Media } from '../../Media/Media';
import { Menu } from '../../Menu/Menu';
import { Modal } from '../../Modal/Modal';
import { Navigation } from '../../Navigation/Navigation';
import { Pagination } from '../../Pagination/Pagination';
import { Panel } from '../../Panel/Panel';
import { Popover } from '../../Popover/Popover';
import { Progress } from '../../Progress/Progress';
import { Radio } from '../../Radio/Radio';
import { Rating } from '../../Rating/Rating';
import { Scroll } from '../../Scroll/Scroll';
import { SegmentedControl } from '../../SegmentedControl/SegmentedControl';
import { Select } from '../../Select/Select';
import { Separator } from '../../Separator/Separator';
import { Skeleton } from '../../Skeleton/Skeleton';
import { Slider } from '../../Slider/Slider';
import { Steps } from '../../Steps/Steps';
import { Switcher } from '../../Switcher/Switcher';
import { Table } from '../../Table/Table';
import { Tabs } from '../../Tabs/Tabs';
import { Text } from '../../Text/Text';
import { Toast } from '../../Toast/Toast';
import { Toc } from '../../Toc/Toc';
import { Tooltip } from '../../Tooltip/Tooltip';
import { Tree } from '../../Tree/Tree';
import { Upload } from '../../Upload/Upload';

export type FeldGalleryEntry = {
  name: string;
  Component: React.ComponentType<any>;
  sampleProps?: Record<string, any>;
};

export const FELD_GALLERY_ENTRIES: FeldGalleryEntry[] = [
  { name: "Accordion", Component: Accordion, sampleProps: {"multiple":false,"collapsible":true,"disabled":false,"items":[{"value":"a","label":"Section A","content":"Content A"},{"value":"b","label":"Section B","content":"Content B"}],"defaultExpandedIds":[]} },
  { name: "Avatar", Component: Avatar, sampleProps: {"src":"","name":"John Doe","fallback":null,"fallbackDelayMs":0} },
  { name: "Badge", Component: Badge, sampleProps: {"text":"Badge","variant":"default","appearance":"fill","children":null} },
  { name: "Bar", Component: Bar, sampleProps: {"children":"Bar content","orientation":"horizontal"} },
  { name: "Breadcrumb", Component: Breadcrumb, sampleProps: {"items":[{"label":"Home","href":"#"},{"label":"Design","href":"#"},{"label":"System","href":"#"},{"label":"Components","href":"#"},{"label":"Navigation","href":"#"},{"label":"Breadcrumb"}],"separator":"/","membrane":true,"allowNavigation":false,"collapseAfter":4} },
  { name: "Button", Component: Button, sampleProps: {"text":"Button","variant":"default","iconPosition":"left","iconOnly":false,"disabled":false,"fullWidth":true,"align":null,"membrane":true,"copyText":null,"children":null} },
  { name: "Calendar", Component: Calendar, sampleProps: {"min":null,"max":null,"locale":"en-US","weekStartsOn":0} },
  { name: "Card", Component: Card, sampleProps: {"title":"Card","description":"Description","content":"Card content","footer":null,"membrane":true,"children":null} },
  { name: "Carousel", Component: Carousel, sampleProps: {"children":["Slide 1","Slide 2","Slide 3"],"loop":false,"autoPlay":false,"autoPlayInterval":3000,"orientation":"horizontal","slidesPerView":1,"defaultIndex":0} },
  { name: "Checkbox", Component: Checkbox, sampleProps: {"defaultChecked":true,"disabled":false,"required":false,"name":"","label":"Checkbox","membrane":true} },
  { name: "Code", Component: Code, sampleProps: {"code":"/* CSS file example */\n\n:root {\n  --uf-color-hover: rgba(0,0,0,0.08);\n}\n\n.button {\n  height: 32px;\n  padding: 0 8px;\n  border-radius: 6px;\n}\n\n/* long tail to test collapse */\n/* line 1 */\\n/* line 2 */\\n/* line 3 */\\n/* line 4 */\\n/* line 5 */\\n/* line 6 */\\n/* line 7 */\\n/* line 8 */\\n/* line 9 */\\n/* line 10 */\\n/* line 11 */\\n/* line 12 */\\n/* line 13 */\\n/* line 14 */\\n/* line 15 */\\n/* line 16 */\\n/* line 17 */\\n/* line 18 */\\n/* line 19 */\\n/* line 20 */","language":"css","title":"Files / Playground","showLineNumbers":false,"highlight":[],"defaultCollapsed":true,"collapsedHeight":160} },
  { name: "Command", Component: Command, sampleProps: {"items":[{"id":"copy","label":"Copy"},{"id":"paste","label":"Paste"},{"id":"cut","label":"Cut"}],"groups":[],"placeholder":"Type a command...","defaultValue":"","surface":"auto","defaultOpen":false,"emptyContent":"No results found."} },
  { name: "DatePicker", Component: DatePicker, sampleProps: {"label":"Date","placeholder":"Pick date"} },
  { name: "Drawer", Component: Drawer, sampleProps: {"side":"bottom","trigger":"Open drawer","title":"Drawer","description":"Directional edge-aligned surface.","children":"Drawer content"} },
  { name: "Icon", Component: Icon, sampleProps: {"name":"settings","size":20,"square":true,"label":null} },
  { name: "Input", Component: Input, sampleProps: {"defaultValue":"","type":"default","textLayout":"scroll","disabled":false,"readOnly":false,"label":"Input","description":null,"error":"","labelOrientation":"vertical","placeholder":"Type…","iconPosition":"left","stretchText":false,"required":false,"membrane":false} },
  { name: "Markdown", Component: Markdown, sampleProps: {"content":"# Markdown Capability Demo\n\nThis single document shows core **Markdown + GFM** features.\n\n## Headings\n### H3\n#### H4\n##### H5\n###### H6\n\n## Emphasis\n- *Italic text*\n- **Bold text**\n- ***Bold italic text***\n- ~~Strikethrough text~~\n- Inline code: `const mode = \"strict\"`\n\n## Links\n- Inline link: [Userface](https://userface.dev)\n- Relative link: [Docs](/docs)\n- Autolink: https://example.com/docs?tab=markdown\n\n## Blockquote\n> Design systems fail when visual rules are optional.\n>\n> Keep primitives consistent and contracts explicit.\n\n## Lists\n- Item A\n- Item B\n  - Item B.1\n  - Item B.2\n\n1. Plan\n2. Implement\n3. Validate\n\n- [x] Parse markdown\n- [x] Sanitize output\n- [ ] Ship release\n\n## Table (GFM)\n| Token | Meaning | Example |\n| :---- | :------ | ------: |\n| `--uf-space-1` | Base micro spacing | 2px |\n| `--uf-control-height` | Control height baseline | 32px |\n\n---\n\n## Code blocks\n```ts\nexport function clamp(value: number, min: number, max: number): number {\n  return Math.min(max, Math.max(min, value))\n}\n```\n\n```bash\npnpm install\npnpm run dev\npnpm run lint\n```\n\n## Image\n![Markdown preview image](https://picsum.photos/800/240 \"Markdown demo image\")\n\n## Escaping\nUse a literal asterisk: \\*not italic\\*","gfm":true,"safeMode":true,"allowRawHtml":false,"linkTarget":"_self","linkRel":"noopener noreferrer","membrane":true,"fullWidth":true} },
  { name: "Media", Component: Media, sampleProps: {"type":"image","src":"/media/images/architecture-preview.jpg","alt":"Architecture sample","variant":"default","lazy":false,"loading":null,"decoding":"async","controls":false,"autoPlay":false,"loop":false,"muted":false,"width":null,"height":null,"objectFit":null} },
  { name: "Menu", Component: Menu, sampleProps: {"trigger":"click","items":[{"value":"edit","label":"Edit"},{"value":"delete","label":"Delete"}],"children":"Menu","disabled":false,"surface":"auto"} },
  { name: "Modal", Component: Modal, sampleProps: {"variant":"center","closeOnOverlayClick":true,"closable":true,"title":"Modal","description":"Focused work surface","children":"Use this surface for edits, confirmations, and contextual flows.","trigger":"Open","width":400,"height":420,"surface":"sheet","actions":[{"label":"Cancel","variant":"outline"},{"label":"Create","variant":"accent"}]} },
  { name: "Navigation", Component: Navigation, sampleProps: {"items":[{"id":"home","label":"Home"},{"id":"library","label":"Library","items":[{"id":"typefaces","label":"Typefaces"},{"id":"components","label":"Components"}]},{"id":"settings","label":"Settings"}],"defaultActiveId":"home","orientation":"horizontal","surface":"auto","defaultOpen":false} },
  { name: "Pagination", Component: Pagination, sampleProps: {"total":120,"pageSize":10,"siblingCount":1,"disabled":false,"membrane":true,"surfaceTitle":"Choose page","defaultPage":6} },
  { name: "Panel", Component: Panel, sampleProps: {"items":[],"defaultCollapsed":false,"width":260,"collapsedWidth":60,"surface":"auto","defaultOpen":false,"previewPreset":"workspace","defaultSelectedId":"overview"} },
  { name: "Popover", Component: Popover, sampleProps: {"interactive":true,"children":"Open popover","content":"Popover content"} },
  { name: "Progress", Component: Progress, sampleProps: {"value":60,"max":100,"variant":"default","showLabel":true,"label":null} },
  { name: "Radio", Component: Radio, sampleProps: {"options":[{"value":"1","label":"Option 1"},{"value":"2","label":"Option 2"}],"disabled":false,"required":false,"orientation":"vertical","membrane":true,"name":"radio","defaultValue":"1"} },
  { name: "Rating", Component: Rating, sampleProps: {"defaultValue":3,"max":5,"disabled":false,"allowHalf":false,"label":null} },
  { name: "Scroll", Component: Scroll, sampleProps: {"children":"Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. Scrollable content. ","type":"auto","orientation":"vertical","height":160,"style":{"height":120}} },
  { name: "SegmentedControl", Component: SegmentedControl, sampleProps: {"selectionMode":"single","items":[{"value":"grid","label":"Grid"},{"value":"list","label":"List"},{"value":"board","label":"Board"}],"defaultValue":["grid"]} },
  { name: "Select", Component: Select, sampleProps: {"options":[{"value":"1","label":"Option 1"},{"value":"2","label":"Option 2"}],"placeholder":"Choose...","disabled":false,"type":"select","labelOrientation":"vertical","stretchText":false,"surface":"auto","membrane":true,"label":"Select","defaultValue":"1"} },
  { name: "Separator", Component: Separator, sampleProps: {"orientation":"horizontal","decorative":true,"membrane":true} },
  { name: "Skeleton", Component: Skeleton, sampleProps: {"width":200,"height":20,"variant":"text"} },
  { name: "Slider", Component: Slider, sampleProps: {"variant":"advanced","min":0,"max":100,"step":1,"disabled":false,"orientation":"horizontal","label":null,"leading":"text","crop":true,"cropLocksValue":true,"defaultValue":[40],"leadingText":"Crop","defaultCropRange":{"min":20,"max":80}} },
  { name: "Steps", Component: Steps, sampleProps: {"items":[{"label":"Account","content":"Create your workspace and owner account."},{"label":"Profile","content":"Add brand settings, themes, and team details."},{"label":"Review","content":"Review the setup before publishing."}],"defaultStep":0,"linear":true,"disabled":false} },
  { name: "Switcher", Component: Switcher, sampleProps: {"disabled":false,"required":false,"name":"","value":"on","label":"Dark mode","withText":true,"textWrap":"truncate","membrane":true,"text":"I accept the End User License Agreement","defaultChecked":false} },
  { name: "Table", Component: Table, sampleProps: {"columns":[{"id":"name","header":"Name","accessor":"name","truncate":true},{"id":"status","header":"Status","accessor":"status"},{"id":"price","header":"Price","accessor":"price","align":"right"}],"rows":[{"id":"r1","name":"Akt Typeface 1.0","status":"Published","price":"₽ 2 990"},{"id":"r2","name":"Werkzeug","status":"Draft","price":"₽ 1 990"},{"id":"r3","name":"A very long row name to test truncation","status":"Archived","price":"—"}],"rowKey":"id","selectable":false,"showRowNumbers":true,"stickyHeader":true,"showDividers":true,"resizable":true,"stickyLastColumn":false} },
  { name: "Tabs", Component: Tabs, sampleProps: {"items":[{"value":"a","label":"Tab A","content":"Content A"},{"value":"b","label":"Tab B","content":"Content B"}],"orientation":"horizontal","activationMode":"automatic","disabled":false,"withLine":false,"wrap":false,"membrane":true,"defaultValue":"a"} },
  { name: "Text", Component: Text, sampleProps: {"text":"Text","variant":"default","size":null,"as":null,"icon":null,"iconPosition":"left","inset":"control","stretchText":false,"fullWidth":false,"align":"left","membrane":true,"children":null} },
  { name: "Toast", Component: Toast, sampleProps: {"className":null,"showTrigger":true,"autoShow":false} },
  { name: "Toc", Component: Toc, sampleProps: {"items":[{"id":"intro","label":"Introduction","level":1},{"id":"setup","label":"Setup","level":1},{"id":"tokens","label":"Design tokens","level":2},{"id":"themes","label":"Themes","level":3},{"id":"usage","label":"Usage","level":1}],"withLine":true,"lineSide":"left","defaultActiveId":"tokens"} },
  { name: "Tooltip", Component: Tooltip, sampleProps: {"children":"Hover me","content":"Tooltip text"} },
  { name: "Tree", Component: Tree, sampleProps: {"items":[{"id":"src","label":"src","children":[{"id":"index","label":"index.ts"},{"id":"utils","label":"utils.ts"}]},{"id":"readme","label":"README.md"}],"defaultExpandedIds":["src"]} },
  { name: "Upload", Component: Upload, sampleProps: {"accept":"","multiple":false,"maxSize":0,"maxFiles":0,"disabled":false} },
];
